name: Test on commit

on:
  workflow_dispatch:
  push:
    paths:
      - src/**
      - pom.xml
      - frontend/ATRA/src
      - frontend/ATRA/package.json
      - frontend/ATRA/angular.json
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run unit tests
        run: mvn test -Dtest=codeurjc_students.ATRA.unit.*Test

      - name: Run integration tests
        run: mvn test -Dtest=codeurjc_students.ATRA.integration.*Test
